secrets:
  client_secret:
    file: ./secrets/client_secret.txt

services:
  app:
    image: portfolio:latest
    secrets:
      - client_secret
    env_file:
      - .env
    environment:
      - CLIENT_SECRET_FILE=/run/secrets/client_secret
    command: gunicorn "__init__:create_app()" --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
    restart: on-failure
