services:
  app:
    image: portfolio:latest
    environment:
      AUTHORIZATION_BASE_URL: ${AUTHORIZATION_BASE_URL:?set on host}
      AWS_REGION: ${AWS_REGION:?set on host}
      AWS_SECRETSMANAGER_SECRET_NAME: ${AWS_SECRETSMANAGER_SECRET_NAME:?set on host}
      AWS_SECRETSMANAGER_SERVICE_NAME: ${AWS_SECRETSMANAGER_SERVICE_NAME:-client_secret}
      CALLBACK_URL: ${CALLBACK_URL:?set on host}
      CLIENT_ID: ${CLIENT_ID:?set on host}
      COOKIE_SAME_SITE: ${COOKIE_SAMESITE:?set on host}
      COOKIE_SECURE: ${COOKIE_SECURE:?set on host}
      SCOPES: ${SCOPES:?set on host}
      TOKEN_URL: ${TOKEN_URL:?set on host}
    command: gunicorn "__init__:create_app()" --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
    restart: on-failure
